//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.View.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.View.Ressources.UserInterface", typeof(UserInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a backup job.
        /// </summary>
        internal static string Add_Header {
            get {
                return ResourceManager.GetString("Add.Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup name:.
        /// </summary>
        internal static string Add_PromptName {
            get {
                return ResourceManager.GetString("Add.PromptName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source directory:.
        /// </summary>
        internal static string Add_PromptSource {
            get {
                return ResourceManager.GetString("Add.PromptSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target directory:.
        /// </summary>
        internal static string Add_PromptTarget {
            get {
                return ResourceManager.GetString("Add.PromptTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup type:.
        /// </summary>
        internal static string Add_PromptType {
            get {
                return ResourceManager.GetString("Add.PromptType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1) Complete   2) Differential.
        /// </summary>
        internal static string Add_TypeOptions {
            get {
                return ResourceManager.GetString("Add.TypeOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup job created..
        /// </summary>
        internal static string Add_Success {
            get {
                return ResourceManager.GetString("Add.Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create the job:.
        /// </summary>
        internal static string Add_Failed {
            get {
                return ResourceManager.GetString("Add.Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum number of jobs reached (5)..
        /// </summary>
        internal static string Add_Error_MaxJobs {
            get {
                return ResourceManager.GetString("Add.Error.MaxJobs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No free slot available (1..5)..
        /// </summary>
        internal static string Add_Error_NoFreeSlot {
            get {
                return ResourceManager.GetString("Add.Error.NoFreeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add backup configuration.
        /// </summary>
        internal static string Menu_AddBackup {
            get {
                return ResourceManager.GetString("Menu.AddBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === EasySave Menu ===.
        /// </summary>
        internal static string Menu_Header {
            get {
                return ResourceManager.GetString("Menu.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch backup job.
        /// </summary>
        internal static string Menu_LaunchBackupJob {
            get {
                return ResourceManager.GetString("Menu.LaunchBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List backup jobs.
        /// </summary>
        internal static string Menu_ListJobs {
            get {
                return ResourceManager.GetString("Menu.ListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove backup configuration.
        /// </summary>
        internal static string Menu_RemoveBackup {
            get {
                return ResourceManager.GetString("Menu.RemoveBackup", resourceCulture);
            }
        }
    }
}
