//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Views.Resources.UserInterface", typeof(UserInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of jobs reached (5)..
        /// </summary>
        internal static string Add_Error_MaxJobs {
            get {
                return ResourceManager.GetString("Add_Error_MaxJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free slot available (1..5)..
        /// </summary>
        internal static string Add_Error_NoFreeSlot {
            get {
                return ResourceManager.GetString("Add_Error_NoFreeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the job:.
        /// </summary>
        internal static string Add_Failed {
            get {
                return ResourceManager.GetString("Add_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a backup job.
        /// </summary>
        internal static string Add_Header {
            get {
                return ResourceManager.GetString("Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup name:.
        /// </summary>
        internal static string Add_PromptName {
            get {
                return ResourceManager.GetString("Add_PromptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory:.
        /// </summary>
        internal static string Add_PromptSource {
            get {
                return ResourceManager.GetString("Add_PromptSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory:.
        /// </summary>
        internal static string Add_PromptTarget {
            get {
                return ResourceManager.GetString("Add_PromptTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type:.
        /// </summary>
        internal static string Add_PromptType {
            get {
                return ResourceManager.GetString("Add_PromptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup job created..
        /// </summary>
        internal static string Add_Success {
            get {
                return ResourceManager.GetString("Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Complete   2) Differential.
        /// </summary>
        internal static string Add_TypeOptions {
            get {
                return ResourceManager.GetString("Add_TypeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled..
        /// </summary>
        internal static string Common_Cancelled {
            get {
                return ResourceManager.GetString("Common_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please try again..
        /// </summary>
        internal static string Common_InvalidInput {
            get {
                return ResourceManager.GetString("Common_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the menu..
        /// </summary>
        internal static string Common_PressAnyKey {
            get {
                return ResourceManager.GetString("Common_PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extension.
        /// </summary>
        internal static string Gui_AddExtension {
            get {
                return ResourceManager.GetString("Gui_AddExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Business Software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Added_Title {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Added_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected.
        /// </summary>
        internal static string Gui_BusinessSoftware_Button_AddSelected {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Button_AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        internal static string Gui_BusinessSoftware_Button_RemoveSelected {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Button_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Added Software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Button_ViewAdded {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Button_ViewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Business Software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Catalog_Title {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Catalog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Search_Label {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to filter software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Search_Placeholder {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software removed from blocker list..
        /// </summary>
        internal static string Gui_BusinessSoftware_Status_Removed {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Status_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software list updated..
        /// </summary>
        internal static string Gui_BusinessSoftware_Status_Updated {
            get {
                return ResourceManager.GetString("Gui_BusinessSoftware_Status_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string Gui_Button_AddJob {
            get {
                return ResourceManager.GetString("Gui_Button_AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse source....
        /// </summary>
        internal static string Gui_Button_BrowseSource {
            get {
                return ResourceManager.GetString("Gui_Button_BrowseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse target....
        /// </summary>
        internal static string Gui_Button_BrowseTarget {
            get {
                return ResourceManager.GetString("Gui_Button_BrowseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Gui_Button_English {
            get {
                return ResourceManager.GetString("Gui_Button_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string Gui_Button_French {
            get {
                return ResourceManager.GetString("Gui_Button_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string Gui_Button_Json {
            get {
                return ResourceManager.GetString("Gui_Button_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        internal static string Gui_Button_RemoveSelected {
            get {
                return ResourceManager.GetString("Gui_Button_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run All Jobs.
        /// </summary>
        internal static string Gui_Button_RunAllJobs {
            get {
                return ResourceManager.GetString("Gui_Button_RunAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Selected Job.
        /// </summary>
        internal static string Gui_Button_RunSelectedJob {
            get {
                return ResourceManager.GetString("Gui_Button_RunSelectedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string Gui_Button_Xml {
            get {
                return ResourceManager.GetString("Gui_Button_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Gui_Menu_Features {
            get {
                return ResourceManager.GetString("Gui_Menu_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Business Software.
        /// </summary>
        internal static string Gui_Menu_ManageBusinessSoftware {
            get {
                return ResourceManager.GetString("Gui_Menu_ManageBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Gui_Menu_Root {
            get {
                return ResourceManager.GetString("Gui_Menu_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Gui_Menu_Settings {
            get {
                return ResourceManager.GetString("Gui_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Gui_Navigation_Back {
            get {
                return ResourceManager.GetString("Gui_Navigation_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSoft key..
        /// </summary>
        internal static string Gui_Settings_CryptoSoftKey {
            get {
                return ResourceManager.GetString("Gui_Settings_CryptoSoftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension to crypt.
        /// </summary>
        internal static string Gui_Settings_ExtensionToCrypt {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionToCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This settings screen is ready for future parameters..
        /// </summary>
        internal static string Gui_Settings_Hint_FutureExtension {
            get {
                return ResourceManager.GetString("Gui_Settings_Hint_FutureExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Gui_Settings_Label {
            get {
                return ResourceManager.GetString("Gui_Settings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string Gui_Settings_Screen_Title {
            get {
                return ResourceManager.GetString("Gui_Settings_Screen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Gui_Settings_Section_Language {
            get {
                return ResourceManager.GetString("Gui_Settings_Section_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        internal static string Gui_Settings_Section_LogType {
            get {
                return ResourceManager.GetString("Gui_Settings_Section_LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &apos;{0}&apos; finished..
        /// </summary>
        internal static string Gui_Status_BackupAsFinished {
            get {
                return ResourceManager.GetString("Gui_Status_BackupAsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &apos;{0}&apos; stopped: business software is running.
        /// </summary>
        internal static string Gui_Status_BackupStoppedByBusinessSoftware {
            get {
                return ResourceManager.GetString("Gui_Status_BackupStoppedByBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to English.
        /// </summary>
        internal static string Gui_Status_LanguageChangedEn {
            get {
                return ResourceManager.GetString("Gui_Status_LanguageChangedEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to French.
        /// </summary>
        internal static string Gui_Status_LanguageChangedFr {
            get {
                return ResourceManager.GetString("Gui_Status_LanguageChangedFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log type set to JSON.
        /// </summary>
        internal static string Gui_Status_LogTypeJsonSet {
            get {
                return ResourceManager.GetString("Gui_Status_LogTypeJsonSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log type set to XML.
        /// </summary>
        internal static string Gui_Status_LogTypeXmlSet {
            get {
                return ResourceManager.GetString("Gui_Status_LogTypeXmlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extension..
        /// </summary>
        internal static string Gui_Tooltip_DeleteExtension {
            get {
                return ResourceManager.GetString("Gui_Tooltip_DeleteExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave - Backup Manager.
        /// </summary>
        internal static string Gui_Window_Title {
            get {
                return ResourceManager.GetString("Gui_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id | Name                 | Type         | Source -&gt; Target.
        /// </summary>
        internal static string Jobs_Columns {
            get {
                return ResourceManager.GetString("Jobs_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute all jobs.
        /// </summary>
        internal static string Jobs_Execute_All {
            get {
                return ResourceManager.GetString("Jobs_Execute_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the job - {0} - {1}.
        /// </summary>
        internal static string Jobs_Execute_Id {
            get {
                return ResourceManager.GetString("Jobs_Execute_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured backup jobs.
        /// </summary>
        internal static string Jobs_Header {
            get {
                return ResourceManager.GetString("Jobs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup job is configured..
        /// </summary>
        internal static string Jobs_None {
            get {
                return ResourceManager.GetString("Jobs_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove job {0} - {1}.
        /// </summary>
        internal static string Jobs_Remove_Id {
            get {
                return ResourceManager.GetString("Jobs_Remove_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution finished..
        /// </summary>
        internal static string Launch_Done {
            get {
                return ResourceManager.GetString("Launch_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch backup.
        /// </summary>
        internal static string Launch_Header {
            get {
                return ResourceManager.GetString("Launch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id..
        /// </summary>
        internal static string Launch_Invalid {
            get {
                return ResourceManager.GetString("Launch_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job not found..
        /// </summary>
        internal static string Launch_NotFound {
            get {
                return ResourceManager.GetString("Launch_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a job id to run, or 0 to run all jobs sequentially:.
        /// </summary>
        internal static string Launch_Prompt {
            get {
                return ResourceManager.GetString("Launch_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running all jobs....
        /// </summary>
        internal static string Launch_RunningAll {
            get {
                return ResourceManager.GetString("Launch_RunningAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running job {0} - {1}....
        /// </summary>
        internal static string Launch_RunningOne {
            get {
                return ResourceManager.GetString("Launch_RunningOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add backup configuration.
        /// </summary>
        internal static string Menu_AddBackup {
            get {
                return ResourceManager.GetString("Menu_AddBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string Menu_Lang {
            get {
                return ResourceManager.GetString("Menu_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch backup job.
        /// </summary>
        internal static string Menu_LaunchBackupJob {
            get {
                return ResourceManager.GetString("Menu_LaunchBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List backup jobs.
        /// </summary>
        internal static string Menu_ListJobs {
            get {
                return ResourceManager.GetString("Menu_ListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Log Type.
        /// </summary>
        internal static string Menu_Log {
            get {
                return ResourceManager.GetString("Menu_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove backup configuration.
        /// </summary>
        internal static string Menu_RemoveBackup {
            get {
                return ResourceManager.GetString("Menu_RemoveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Change Language ===.
        /// </summary>
        internal static string Menu_Title_Lang {
            get {
                return ResourceManager.GetString("Menu_Title_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Choose a Log Type ===.
        /// </summary>
        internal static string Menu_Title_LogType {
            get {
                return ResourceManager.GetString("Menu_Title_LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === EasySave Menu ===.
        /// </summary>
        internal static string Menu_Title_Main {
            get {
                return ResourceManager.GetString("Menu_Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Remove a backup Job ===.
        /// </summary>
        internal static string Menu_Title_RemoveJob {
            get {
                return ResourceManager.GetString("Menu_Title_RemoveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Start a save ===.
        /// </summary>
        internal static string Menu_Title_StartJob {
            get {
                return ResourceManager.GetString("Menu_Title_StartJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory does not exist. Please enter an existing directory..
        /// </summary>
        internal static string Path_SourceNotFound {
            get {
                return ResourceManager.GetString("Path_SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory does not exist. Please enter an existing directory..
        /// </summary>
        internal static string Path_TargetNotFound {
            get {
                return ResourceManager.GetString("Path_TargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a backup job.
        /// </summary>
        internal static string Remove_Header {
            get {
                return ResourceManager.GetString("Remove_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching job found..
        /// </summary>
        internal static string Remove_NotFound {
            get {
                return ResourceManager.GetString("Remove_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a job id (e.g. 1) or a job name:.
        /// </summary>
        internal static string Remove_Prompt {
            get {
                return ResourceManager.GetString("Remove_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job removed..
        /// </summary>
        internal static string Remove_Success {
            get {
                return ResourceManager.GetString("Remove_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to menu.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} not found..
        /// </summary>
        internal static string Terminal_Log_JobIdNotFound {
            get {
                return ResourceManager.GetString("Terminal_Log_JobIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} skipped: source directory not found..
        /// </summary>
        internal static string Terminal_Log_JobSourceNotFound {
            get {
                return ResourceManager.GetString("Terminal_Log_JobSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} skipped: target directory not found..
        /// </summary>
        internal static string Terminal_Log_JobTargetNotFound {
            get {
                return ResourceManager.GetString("Terminal_Log_JobTargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup job configured..
        /// </summary>
        internal static string Terminal_Log_NoJobConfigured {
            get {
                return ResourceManager.GetString("Terminal_Log_NoJobConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Terminal_Log_Usage {
            get {
                return ResourceManager.GetString("Terminal_Log_Usage", resourceCulture);
            }
        }
    }
}
