//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Views.Resources.UserInterface", typeof(UserInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of jobs reached (5)..
        /// </summary>
        internal static string Add_Error_MaxJobs {
            get {
                return ResourceManager.GetString("Add.Error.MaxJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free slot available (1..5)..
        /// </summary>
        internal static string Add_Error_NoFreeSlot {
            get {
                return ResourceManager.GetString("Add.Error.NoFreeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the job:.
        /// </summary>
        internal static string Add_Failed {
            get {
                return ResourceManager.GetString("Add.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a backup job.
        /// </summary>
        internal static string Add_Header {
            get {
                return ResourceManager.GetString("Add.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup name:.
        /// </summary>
        internal static string Add_PromptName {
            get {
                return ResourceManager.GetString("Add.PromptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory:.
        /// </summary>
        internal static string Add_PromptSource {
            get {
                return ResourceManager.GetString("Add.PromptSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory:.
        /// </summary>
        internal static string Add_PromptTarget {
            get {
                return ResourceManager.GetString("Add.PromptTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type:.
        /// </summary>
        internal static string Add_PromptType {
            get {
                return ResourceManager.GetString("Add.PromptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup job created..
        /// </summary>
        internal static string Add_Success {
            get {
                return ResourceManager.GetString("Add.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Complete   2) Differential.
        /// </summary>
        internal static string Add_TypeOptions {
            get {
                return ResourceManager.GetString("Add.TypeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled..
        /// </summary>
        internal static string Common_Cancelled {
            get {
                return ResourceManager.GetString("Common.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please try again..
        /// </summary>
        internal static string Common_InvalidInput {
            get {
                return ResourceManager.GetString("Common.InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the menu..
        /// </summary>
        internal static string Common_PressAnyKey {
            get {
                return ResourceManager.GetString("Common.PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extension.
        /// </summary>
        internal static string Gui_AddExtension {
            get {
                return ResourceManager.GetString("Gui.AddExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Business Software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Added_Title {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Added.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected.
        /// </summary>
        internal static string Gui_BusinessSoftware_Button_AddSelected {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Button.AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        internal static string Gui_BusinessSoftware_Button_RemoveSelected {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Button.RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Added Software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Button_ViewAdded {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Button.ViewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Business Software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Catalog_Title {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Catalog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Search_Label {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Search.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to filter software.
        /// </summary>
        internal static string Gui_BusinessSoftware_Search_Placeholder {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Search.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software removed from blocker list..
        /// </summary>
        internal static string Gui_BusinessSoftware_Status_Removed {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Status.Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software list updated..
        /// </summary>
        internal static string Gui_BusinessSoftware_Status_Updated {
            get {
                return ResourceManager.GetString("Gui.BusinessSoftware.Status.Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string Gui_Button_AddJob {
            get {
                return ResourceManager.GetString("Gui.Button.AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse source....
        /// </summary>
        internal static string Gui_Button_BrowseSource {
            get {
                return ResourceManager.GetString("Gui.Button.BrowseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse target....
        /// </summary>
        internal static string Gui_Button_BrowseTarget {
            get {
                return ResourceManager.GetString("Gui.Button.BrowseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Gui_Button_English {
            get {
                return ResourceManager.GetString("Gui.Button.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string Gui_Button_French {
            get {
                return ResourceManager.GetString("Gui.Button.French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string Gui_Button_Json {
            get {
                return ResourceManager.GetString("Gui.Button.Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        internal static string Gui_Button_RemoveSelected {
            get {
                return ResourceManager.GetString("Gui.Button.RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run All Jobs.
        /// </summary>
        internal static string Gui_Button_RunAllJobs {
            get {
                return ResourceManager.GetString("Gui.Button.RunAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Selected Job.
        /// </summary>
        internal static string Gui_Button_RunSelectedJob {
            get {
                return ResourceManager.GetString("Gui.Button.RunSelectedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string Gui_Button_Xml {
            get {
                return ResourceManager.GetString("Gui.Button.Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Gui_Menu_Features {
            get {
                return ResourceManager.GetString("Gui.Menu.Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Business Software.
        /// </summary>
        internal static string Gui_Menu_ManageBusinessSoftware {
            get {
                return ResourceManager.GetString("Gui.Menu.ManageBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Gui_Menu_Root {
            get {
                return ResourceManager.GetString("Gui.Menu.Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Gui_Menu_Settings {
            get {
                return ResourceManager.GetString("Gui.Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Gui_Navigation_Back {
            get {
                return ResourceManager.GetString("Gui.Navigation.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSoft key..
        /// </summary>
        internal static string Gui_Settings_CryptoSoftKey {
            get {
                return ResourceManager.GetString("Gui.Settings.CryptoSoftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension to crypt.
        /// </summary>
        internal static string Gui_Settings_ExtensionToCrypt {
            get {
                return ResourceManager.GetString("Gui.Settings.ExtensionToCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This settings screen is ready for future parameters..
        /// </summary>
        internal static string Gui_Settings_Hint_FutureExtension {
            get {
                return ResourceManager.GetString("Gui.Settings.Hint.FutureExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Gui_Settings_Label {
            get {
                return ResourceManager.GetString("Gui.Settings.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string Gui_Settings_Screen_Title {
            get {
                return ResourceManager.GetString("Gui.Settings.Screen.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Gui_Settings_Section_Language {
            get {
                return ResourceManager.GetString("Gui.Settings.Section.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        internal static string Gui_Settings_Section_LogType {
            get {
                return ResourceManager.GetString("Gui.Settings.Section.LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &apos;{0}&apos; finished..
        /// </summary>
        internal static string Gui_Status_BackupAsFinished {
            get {
                return ResourceManager.GetString("Gui.Status.BackupAsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &apos;{0}&apos; stopped: business software is running.
        /// </summary>
        internal static string Gui_Status_BackupStoppedByBusinessSoftware {
            get {
                return ResourceManager.GetString("Gui.Status.BackupStoppedByBusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to English.
        /// </summary>
        internal static string Gui_Status_LanguageChangedEn {
            get {
                return ResourceManager.GetString("Gui.Status.LanguageChangedEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to French.
        /// </summary>
        internal static string Gui_Status_LanguageChangedFr {
            get {
                return ResourceManager.GetString("Gui.Status.LanguageChangedFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log type set to JSON.
        /// </summary>
        internal static string Gui_Status_LogTypeJsonSet {
            get {
                return ResourceManager.GetString("Gui.Status.LogTypeJsonSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log type set to XML.
        /// </summary>
        internal static string Gui_Status_LogTypeXmlSet {
            get {
                return ResourceManager.GetString("Gui.Status.LogTypeXmlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extension..
        /// </summary>
        internal static string Gui_Tooltip_DeleteExtension {
            get {
                return ResourceManager.GetString("Gui.Tooltip.DeleteExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave - Backup Manager.
        /// </summary>
        internal static string Gui_Window_Title {
            get {
                return ResourceManager.GetString("Gui.Window.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id | Name                 | Type         | Source -&gt; Target.
        /// </summary>
        internal static string Jobs_Columns {
            get {
                return ResourceManager.GetString("Jobs.Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute all jobs.
        /// </summary>
        internal static string Jobs_Execute_All {
            get {
                return ResourceManager.GetString("Jobs.Execute.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the job - {0} - {1}.
        /// </summary>
        internal static string Jobs_Execute_ID {
            get {
                return ResourceManager.GetString("Jobs.Execute.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured backup jobs.
        /// </summary>
        internal static string Jobs_Header {
            get {
                return ResourceManager.GetString("Jobs.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup job is configured..
        /// </summary>
        internal static string Jobs_None {
            get {
                return ResourceManager.GetString("Jobs.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove job {0} - {1}.
        /// </summary>
        internal static string Jobs_Remove_ID {
            get {
                return ResourceManager.GetString("Jobs.Remove.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution finished..
        /// </summary>
        internal static string Launch_Done {
            get {
                return ResourceManager.GetString("Launch.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch backup.
        /// </summary>
        internal static string Launch_Header {
            get {
                return ResourceManager.GetString("Launch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id..
        /// </summary>
        internal static string Launch_Invalid {
            get {
                return ResourceManager.GetString("Launch.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job not found..
        /// </summary>
        internal static string Launch_NotFound {
            get {
                return ResourceManager.GetString("Launch.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a job id to run, or 0 to run all jobs sequentially:.
        /// </summary>
        internal static string Launch_Prompt {
            get {
                return ResourceManager.GetString("Launch.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running all jobs....
        /// </summary>
        internal static string Launch_RunningAll {
            get {
                return ResourceManager.GetString("Launch.RunningAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running job {0} - {1}....
        /// </summary>
        internal static string Launch_RunningOne {
            get {
                return ResourceManager.GetString("Launch.RunningOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add backup configuration.
        /// </summary>
        internal static string Menu_AddBackup {
            get {
                return ResourceManager.GetString("Menu.AddBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string Menu_Lang {
            get {
                return ResourceManager.GetString("Menu.Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch backup job.
        /// </summary>
        internal static string Menu_LaunchBackupJob {
            get {
                return ResourceManager.GetString("Menu.LaunchBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List backup jobs.
        /// </summary>
        internal static string Menu_ListJobs {
            get {
                return ResourceManager.GetString("Menu.ListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Log Type.
        /// </summary>
        internal static string Menu_Log {
            get {
                return ResourceManager.GetString("Menu.Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove backup configuration.
        /// </summary>
        internal static string Menu_RemoveBackup {
            get {
                return ResourceManager.GetString("Menu.RemoveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Change Language ===.
        /// </summary>
        internal static string Menu_Title_Lang {
            get {
                return ResourceManager.GetString("Menu.Title.Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Choose a Log Type ===.
        /// </summary>
        internal static string Menu_Title_LogType {
            get {
                return ResourceManager.GetString("Menu.Title.LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === EasySave Menu ===.
        /// </summary>
        internal static string Menu_Title_Main {
            get {
                return ResourceManager.GetString("Menu.Title.Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Remove a backup Job ===.
        /// </summary>
        internal static string Menu_Title_RemoveJob {
            get {
                return ResourceManager.GetString("Menu.Title.RemoveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Start a save ===.
        /// </summary>
        internal static string Menu_Title_StartJob {
            get {
                return ResourceManager.GetString("Menu.Title.StartJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory does not exist. Please enter an existing directory..
        /// </summary>
        internal static string Path_SourceNotFound {
            get {
                return ResourceManager.GetString("Path.SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory does not exist. Please enter an existing directory..
        /// </summary>
        internal static string Path_TargetNotFound {
            get {
                return ResourceManager.GetString("Path.TargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a backup job.
        /// </summary>
        internal static string Remove_Header {
            get {
                return ResourceManager.GetString("Remove.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching job found..
        /// </summary>
        internal static string Remove_NotFound {
            get {
                return ResourceManager.GetString("Remove.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a job id (e.g. 1) or a job name:.
        /// </summary>
        internal static string Remove_Prompt {
            get {
                return ResourceManager.GetString("Remove.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job removed..
        /// </summary>
        internal static string Remove_Success {
            get {
                return ResourceManager.GetString("Remove.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to menu.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} not found..
        /// </summary>
        internal static string Terminal_log_JobIdNotFound {
            get {
                return ResourceManager.GetString("Terminal.log.JobIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} skipped: source directory not found..
        /// </summary>
        internal static string Terminal_log_JobSourceNotFound {
            get {
                return ResourceManager.GetString("Terminal.log.JobSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} skipped: target directory not found..
        /// </summary>
        internal static string Terminal_log_JobTargetNotFound {
            get {
                return ResourceManager.GetString("Terminal.log.JobTargetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup job configured..
        /// </summary>
        internal static string Terminal_log_NoJobConfigured {
            get {
                return ResourceManager.GetString("Terminal.log.NoJobConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Terminal_log_Usage {
            get {
                return ResourceManager.GetString("Terminal.log.Usage", resourceCulture);
            }
        }
    }
}
